name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build
        run: |
          gcc -O2 -Wall -Wextra -std=c11 biblioteca.c -o biblioteca
          file ./biblioteca || true

      - name: Upload artifact (binary)
        uses: actions/upload-artifact@v4
        with:
          name: biblioteca-linux
          path: ./biblioteca